[package]
name = "brigde"
version = "0.0.1"
authors = ["Cuong Thach Sam Corp"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = { version = "4.0.0-pre.9", features = ["unstable"] }
near-contract-standards = "4.0.0-pre.9"
hex = "0.4.3"
arrayref = "0.3.6"